apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "alertflow.fullname" . }}-backend-config"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
data:
  DB_SERVER: {{ .Values.backend.env.DB_SERVER }}
  DB_PORT: {{ .Values.backend.env.DB_PORT }}
  DB_USER: {{ .Values.backend.env.DB_USER }}
  DB_PASS: {{ .Values.backend.env.DB_PASS }}
  DB_TABLE: {{ .Values.backend.env.DB_TABLE }}
  JWT_KEY: {{ .Values.backend.env.JWT_KEY }}