apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "alertflow.fullname" . }}-runners"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "alertflow.runners.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "alertflow.fullname" . }}-runners"
        app.kubernetes.io/instance: "{{ include "alertflow.fullname" . }}-runners"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- range .Values.runners.runners }}
        - name: runner-{{ .name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.runners.image }}:{{ .Values.runners.tag }}"
          imagePullPolicy: {{ .Values.runners.pullPolicy }}
          env:
            - name: ALERTFLOW_URL
              value: "https://alertflow.org"
            - name: RUNNER_ID
              value: "{{ .env.RUNNER_ID }}"
            - name: ALERTFLOW_APIKEY
              value: "{{ .env.ALERTFLOW_APIKEY }}"
            - name: PAYLOADS_ENABLED
              value: "{{ .env.PAYLOADS_ENABLED }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
