apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertflow.fullname" . }}
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alertflow.service.type }}
  ports:
    {{- if .Values.alertflow.service.ports.frontend }}
    - port: {{ .Values.alertflow.service.ports.frontend.port }}
      targetPort: {{ .Values.alertflow.service.ports.frontend.targetPort }}
      protocol: TCP
      name: {{ .Values.alertflow.service.ports.frontend.name }}
    {{- end }}
    {{- if .Values.alertflow.service.ports.backend }}
    - port: {{ .Values.alertflow.service.ports.backend.port }}
      targetPort: {{ .Values.alertflow.service.ports.backend.targetPort }}
      protocol: TCP
      name: {{ .Values.alertflow.service.ports.backend.name }}
    {{- end }}
  selector:
    {{- include "alertflow.alertflow.selectorLabels" . | nindent 4 }}
