{{- if .Values.alertflowRunner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "alertflow.fullname" . }}-alertflow-runner-config"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml $.Values.alertflowRunner.configMap.data | nindent 4 }}
{{- end }}