apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertflow.fullname" . }}-backend
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.target_port }}
      protocol: TCP
      name: backend
  selector:
    {{- include "alertflow.backend.selectorLabels" . | nindent 4 }}
