apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "alertflow.fullname" . }}-postgres"
  labels:
    app.kubernetes.io/name: "{{ include "alertflow.fullname" . }}-postgres"
    app.kubernetes.io/instance: "{{ include "alertflow.fullname" . }}-postgres"
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "alertflow.fullname" . }}-postgres"
      app.kubernetes.io/instance: "{{ include "alertflow.fullname" . }}-postgres"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "alertflow.fullname" . }}-postgres"
        app.kubernetes.io/instance: "{{ include "alertflow.fullname" . }}-postgres"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: database
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.database.image }}:{{ .Values.database.tag }}"
          imagePullPolicy: {{ .Values.database.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: alertflow-postgres-config
          {{- if not .Values.database.persistentVolume.enabled }}
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.database.persistentVolume.enabled }}
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: "{{ include "alertflow.fullname" . }}-postgres-pvc"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
