apiVersion: v1
kind: Service
metadata:
  name: "{{ include "alertflow.fullname" . }}-postgres"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.target_port }}
      protocol: TCP
      name: postgres
  selector:
    - "app.kubernetes.io/name={{ include "alertflow.fullname" . }}-postgres"
    - "app.kubernetes.io/instance={{ include "alertflow.fullname" . }}-postgres"
