apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertflow.fullname" . }}-frontend
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alertflow.service.type }}
  ports:
    {{- range .Values.alertflow.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "alertflow.alertflow.selectorLabels" . | nindent 4 }}
