{{- if .Values.runner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.runner.service.type }}
  ports:
    - port: {{ .Values.runner.service.port }}
      targetPort: {{ .Values.runner.service.target_port }}
      protocol: TCP
      name: alertflow-runner
  selector:
    {{- include "alertflow.runner.selectorLabels" . | nindent 4 }}
{{- end }}