{{- if .Values.runner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "alertflow.runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "alertflow.fullname" . }}-runner"
        app.kubernetes.io/instance: "{{ include "alertflow.fullname" . }}-runner"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: runner
          image: "{{ .Values.runner.repository }}:{{ .Values.runner.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runner.pullPolicy }}
          ports:
            - containerPort: {{ .Values.runner.service.target_port }}
          {{- if .Values.runner.configMap.enabled }}
          volumeMounts:
            - name: runnerconfig
              mountPath: /runner/config/config.yaml
              subPath: config.yaml
              readOnly: true
          {{- end }}
      {{- if .Values.runner.configMap.enabled }}
      volumes:
        - name: runnerconfig
          configMap:
            name: {{ include "alertflow.fullname" . }}-runner-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
