{{- if .Values.projectRunner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "alertflow.fullname" . }}-{{ .Values.projectRunner.service.name }}"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.projectRunner.service.type }}
  ports:
    - port: {{ .Values.projectRunner.service.port }}
      targetPort: {{ .Values.projectRunner.service.target_port }}
      protocol: TCP
      name: alertflow-runner
  selector:
    {{- include "alertflow.projectRunner.selectorLabels" . | nindent 4 }}
{{- end }}