apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner-config"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: info
    mode: master

    alertflow:
      url: https://alertflow.org
      apiKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJydW5uZXJfaWQiOiIiLCJwcm9qZWN0X2lkIjoiMzlkNGZjZGYtYmNlYi00MWE2LWE4MjgtNWE3MjNhNDUyZjNhIiwiaWQiOiJkYmZhYjhlZS0wM2YyLTRkOGEtYjY5My0xZmJhZGQ3ODcyZWUiLCJ0eXBlIjoicHJvamVjdF9hdXRvX3J1bm5lciIsImV4cCI6MzMxMjk4NzUwNn0.fSw8VqJZIboTGYxNz7fEoeZdv-wi7j8P79mt0Y-YCr8

    payload_endpoints:
      port: 8081