{{- if and (.Values.projectRunner.enabled) (.Values.projectRunner.persistence.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner-plugin-pvc"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - {{ .Values.projectRunner.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.projectRunner.persistence.size }}
{{- end }}