apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner-plugin-pvc"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi