{{- if and (.Values.projectRunner.enabled) (.Values.projectRunner.configMap.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "alertflow.fullname" . }}-runner-config"
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
data:
  config: {{ .Values.projectRunner.configMap.data }}
{{- end }}