# Default values for alertflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

# My Custom Space

frontend:
  repository: harbor.justlab.xyz/alertflow/frontend
  pullPolicy: Always
  tag: "v0.20.1-beta"
  service:
    type: ClusterIP
    port: 80
    target_port: 3000

backend:
  repository: harbor.justlab.xyz/alertflow/backend
  pullPolicy: Always
  tag: ""
  service:
    type: ClusterIP
    port: 8080
    target_port: 8080
  env:
    DB_SERVER: alertflow-postgres
    DB_PORT: 5432
    DB_USER: alertflow
    DB_PASS: password
    DB_NAME: alertflow
    JWT_KEY: ""

database:
  enabled: true
  image: postgres
  pullPolicy: Always
  tag: "16-alpine"
  replicaCount: 1
  persistentVolume:
    enabled: true
    size: 50Gi
  env:
    POSTGRES_DB: alertflow
    POSTGRES_USER: alertflow
    POSTGRES_PASSWORD: password
  service:
    type: ClusterIP
    port: 5432
    target_port: 5432

runners:
  enabled: true
  service:
    type: ClusterIP
    port: 8081
    target_port: 8081
  containers:
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "v0.4.0-beta"
      env:
        RUNNER_ID: "3401314e-4fe3-4430-b6e7-eda9904510fb"
        ALERTFLOW_URL: "https://alertflow.org"
        ALERTFLOW_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiNTA2MGJiNzMtNmM4OC00YzEyLThiZmEtNTY4MzA4YjY5M2M5IiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzMwMDg1ODIzM30.NlR3IrAdDc7v47RaqDD3sUpyxXR_NhfpAjkWZotd3kk"
        PAYLOADS_PORT: 8081
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "v0.4.0-beta"
      env:
        RUNNER_ID: "595bbb53-22a2-4dd4-ac55-5077782f4aa9"
        ALERTFLOW_URL: "https://alertflow.org"
        ALERTFLOW_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiMTE1MTFhYzAtOGZkZi00NGM3LThhYWUtN2YwNWUzNjgyZjUyIiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzMwMDg1ODI1M30.U_PoMUSCDE_UMXkzJIH0m5QjUL6S7HuD9bSb035Ka6k"
        PAYLOADS_PORT: 8081
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "v0.4.0-beta"
      env:
        RUNNER_ID: "75bb5a4a-524b-452a-bdff-20d6e7c530b7"
        ALERTFLOW_URL: "https://alertflow.org"
        ALERTFLOW_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiYTY0YzRhNzAtNWQ1NS00OTEyLWE3ZjktM2YxY2U0YzQwNTIyIiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzMwMDg1ODI2OH0.DEIT0G8257P7sNywNwX1zB_k1SBnkHy0foXBu65su04"
        PAYLOADS_PORT: 8081

# My Custom Space end

imagePullSecrets:
  - name: docker-cfg
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: alertflow.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: alertflow-frontend
          servicePort: 80
        - path: /api
          pathType: ImplementationSpecific
          serviceName: alertflow-backend
          servicePort: 8080
        - path: /payloads
          pathType: ImplementationSpecific
          serviceName: alertflow-runners
          servicePort: 8081
    - host: www.alertflow.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: alertflow-frontend
          servicePort: 80
        - path: /api
          pathType: ImplementationSpecific
          serviceName: alertflow-backend
          servicePort: 8080
        - path: /payloads
          pathType: ImplementationSpecific
          serviceName: alertflow-runners
          servicePort: 8081
  tls:
    - secretName: alertflow-org-tls
      hosts:
        - alertflow.org
        - www.alertflow.org

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 400m
  #   memory: 768Mi
  requests:
    cpu: 400m
    memory: 768Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
