# Default values for alertflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

# My Custom Space

frontend:
  repository: harbor.justlab.xyz/alertflow/frontend
  pullPolicy: Always
  tag: ""
  service:
    type: ClusterIP
    port: 80
    target_port: 3000

backend:
  repository: harbor.justlab.xyz/alertflow/backend
  pullPolicy: Always
  tag: ""
  configMap:
    enabled: true
  service:
    type: ClusterIP
    port: 8080
    target_port: 8080

database:
  enabled: true
  image: postgres
  pullPolicy: Always
  tag: "16-alpine"
  replicaCount: 1
  persistentVolume:
    enabled: true
    size: 50Gi
  env:
    POSTGRES_DB: alertflow
    POSTGRES_USER: alertflow
    POSTGRES_PASSWORD: password
  service:
    type: ClusterIP
    port: 5432
    target_port: 5432

runners:
  enabled: true
  repository: harbor.justlab.xyz/alertflow/backend
  pullPolicy: Always
  tag: "v0.8.0-beta"
  configMap:
    enabled: true
  service:
    type: ClusterIP
    port: 8081
    target_port: 8081

# My Custom Space end

imagePullSecrets:
  - name: docker-cfg
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: alertflow.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: alertflow-frontend
          servicePort: 80
        - path: /api
          pathType: ImplementationSpecific
          serviceName: alertflow-backend
          servicePort: 8080
        - path: /payloads
          pathType: ImplementationSpecific
          serviceName: alertflow-runners
          servicePort: 8081
    - host: www.alertflow.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: alertflow-frontend
          servicePort: 80
        - path: /api
          pathType: ImplementationSpecific
          serviceName: alertflow-backend
          servicePort: 8080
        - path: /payloads
          pathType: ImplementationSpecific
          serviceName: alertflow-runners
          servicePort: 8081
  tls:
    - secretName: alertflow-org-tls
      hosts:
        - alertflow.org
        - www.alertflow.org

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 400m
  #   memory: 768Mi
  requests:
    cpu: 400m
    memory: 768Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
