# Default values for alertflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

# My Custom Space

frontend:
  repository: harbor.justlab.xyz/alertflow/frontend
  pullPolicy: Always
  tag: "v0.17.1-beta"

  service:
    type: ClusterIP
    port: 80
    target_port: 3000

backend:
  repository: harbor.justlab.xyz/alertflow/backend
  pullPolicy: Always
  tag: ""

  service:
    type: ClusterIP
    port: 8080
    target_port: 8080
  
  env:
    DB_SERVER: alertflow-postgres
    DB_PORT: 5432
    DB_USER: alertflow
    DB_PASS: password
    DB_NAME: alertflow
    JWT_KEY: ""

database:
  enabled: true
  image: postgres
  pullPolicy: Always
  tag: "16-alpine"
  replicaCount: 1
  persistentVolume:
    enabled: true
    size: 50Gi
  env:
    POSTGRES_DB: alertflow
    POSTGRES_USER: alertflow
    POSTGRES_PASSWORD: password
  service:
    type: ClusterIP
    port: 5432
    target_port: 5432

runners:
  enabled: true
  service:
    type: ClusterIP
    port: 8081
    target_port: 8081
  containers:
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "latest"
      env:
        RUNNER_ID: "06921c6d-ad25-441c-8940-9ea9d5f5300b"
        ALERTFLOW_APIKEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiMzAzYWI3MjAtZWE0ZS00MWU4LTllNDktMjIxMjg0OWYyMWIxIiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzI5ODgwNDU0NH0.kUHWg6uYwdXkaxaniKIOCSgst1-rE7-SKsvz40xGeDM"
        PAYLOADS_ENABLED: true
        PAYLOADS_PORT: 8081
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "latest"
      env:
        RUNNER_ID: "d75a13a1-0829-4473-b781-e56cff3dc1ef"
        ALERTFLOW_APIKEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiOGFjMjM4NjEtNTE3MC00YzdjLTgyMGEtYWFhOTJjYjc0ZDdlIiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzI5ODgwODQzNH0.-s8q4W-lfSggMZIstKu86MrfitqE3j9aHp-eFFaja-M"
        PAYLOADS_ENABLED: true
        PAYLOADS_PORT: 8081
    - image: harbor.justlab.xyz/alertflow/runner
      pullPolicy: Always
      tag: "latest"
      env:
        RUNNER_ID: "78465f1e-0436-4827-b7b4-eab00ca08cfe"
        ALERTFLOW_APIKEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoibm9uZSIsImlkIjoiNDAxMDk0YmItMjAzZi00YTUwLWE1ODAtZTFmNjQ0NjczY2ViIiwidHlwZSI6InJ1bm5lciIsImV4cCI6MzI5ODgwODQ1MH0.KXDI9WXaPBsXBkAJaT8QnjfzNraRnL7B15uSlzSIriY"
        PAYLOADS_ENABLED: true
        PAYLOADS_PORT: 8081

# My Custom Space end

imagePullSecrets:
  - name: docker-cfg
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: alertflow.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: alertflow
          servicePort: 80
        - path: /api
          pathType: ImplementationSpecific
          serviceName: alertflow
          servicePort: 8080
        - path: /payloads
          pathType: ImplementationSpecific
          serviceName: alertflow-runners
          servicePort: 8081
  tls:
    - secretName: alertflow-org-tls
      hosts:
        - alertflow.org

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 400m
  #   memory: 768Mi
  requests:
    cpu: 400m
    memory: 768Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
